version: '3'
services:
  mysql-demo:
    container_name: school_registration_demo_db
    hostname: school_registration_demo_db
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "school_registration"
      MYSQL_USER: "school_db_user"
      MYSQL_PASSWORD: "p@55w0rd"
    ports:
      - "5306:3306"
    volumes:
      - "./db-init:/docker-entrypoint-initdb.d"
      - db-demo:/var/lib/minesql
    networks:
      - school_registration-demo-network
  api-demo:
    container_name: school_registration_api
    hostname: school_registration_api
    restart: unless-stopped
    build:
      context: ../school-registration-launcher
      dockerfile: Dockerfile
    ports:
      - "9090:8080"
    environment:
      MYSQL_URL: jdbc:mysql://school_registration_demo_db:3306/school_registration
      MYSQL_USERNAME: school_db_user
      MYSQL_PASSWORD: p@55w0rd
    depends_on:
      - mysql-demo
    networks:
      - school_registration-demo-network

networks:
  school_registration-demo-network:
      driver: bridge

volumes:
  db-demo:
    driver: local
