 INSERT INTO students (name) VALUES ('Roselia Mosciski IV');
 INSERT INTO students (name) VALUES ('Rey Waters');
 INSERT INTO students (name) VALUES ('Bennett Jakubowski');
 INSERT INTO students (name) VALUES ('Miss Jason Ankunding');
 INSERT INTO students (name) VALUES ('Chung Graham');
 INSERT INTO students (name) VALUES ('Dr. Judson Pollich');
 INSERT INTO students (name) VALUES ('Dr. Tasha Jacobi');
 INSERT INTO students (name) VALUES ('Ceola Schneider PhD');
 INSERT INTO students (name) VALUES ('Lou Gleichner DVM');
 INSERT INTO students (name) VALUES ('Bobby Morissette');
 INSERT INTO students (name) VALUES ('Maxwell Rowe');
 INSERT INTO students (name) VALUES ('Alfonzo Mohr MD');
 INSERT INTO students (name) VALUES ('Cletus Stracke');
 INSERT INTO students (name) VALUES ('Clement Feil');
 INSERT INTO students (name) VALUES ('Perry Witting III');
 INSERT INTO students (name) VALUES ('Terrell Langworth');
 INSERT INTO students (name) VALUES ('Wilhemina Walker');
 INSERT INTO students (name) VALUES ('Dr. Anna Beatty');
 INSERT INTO students (name) VALUES ('Shane Orn');
 INSERT INTO students (name) VALUES ('Gayle Yundt');
 INSERT INTO students (name) VALUES ('Vashti Cruickshank DDS');
 INSERT INTO students (name) VALUES ('Son Heathcote');
 INSERT INTO students (name) VALUES ('Karry Hudson');
 INSERT INTO students (name) VALUES ('Terrell Lesch');
 INSERT INTO students (name) VALUES ('Christoper Wilderman');
 INSERT INTO students (name) VALUES ('Daisy Davis Sr.');
 INSERT INTO students (name) VALUES ('Emery Harber');
 INSERT INTO students (name) VALUES ('Russell Cremin');
 INSERT INTO students (name) VALUES ('Dawne Collier');
 INSERT INTO students (name) VALUES ('Dave Cruickshank');
 INSERT INTO students (name) VALUES ('Jacques Friesen');
 INSERT INTO students (name) VALUES ('Alonzo Quigley');
 INSERT INTO students (name) VALUES ('Rochell Hodkiewicz');
 INSERT INTO students (name) VALUES ('Rudy Wolff');
 INSERT INTO students (name) VALUES ('Tamara Monahan');
 INSERT INTO students (name) VALUES ('Berenice Tromp');
 INSERT INTO students (name) VALUES ('Michell Haley');
 INSERT INTO students (name) VALUES ('Donovan Yundt');
 INSERT INTO students (name) VALUES ('Clement Frami');
 INSERT INTO students (name) VALUES ('Kurtis Turcotte');
 INSERT INTO students (name) VALUES ('Jolie Heller');
 INSERT INTO students (name) VALUES ('Danuta Bogisich IV');
 INSERT INTO students (name) VALUES ('Miss Vivan Koss');
 INSERT INTO students (name) VALUES ('Mrs. Desire West');
 INSERT INTO students (name) VALUES ('Jeff Beier');
 INSERT INTO students (name) VALUES ('Arturo Auer');
 INSERT INTO students (name) VALUES ('Ms. Erlinda Gislason');
 INSERT INTO students (name) VALUES ('Leola Purdy');
 INSERT INTO students (name) VALUES ('Arnoldo Keebler');
 INSERT INTO students (name) VALUES ('Miss Maybell Stamm');
 INSERT INTO students (name) VALUES ('Kourtney Rosenbaum');
 INSERT INTO students (name) VALUES ('Selma Mills V');
 INSERT INTO students (name) VALUES ('Dr. Mckinley Zemlak');
 INSERT INTO students (name) VALUES ('Deloras Schowalter');
 INSERT INTO students (name) VALUES ('Theodore Nader');
 INSERT INTO students (name) VALUES ('Bernarda Effertz');
 INSERT INTO students (name) VALUES ('Stan Schultz');
 INSERT INTO students (name) VALUES ('Matthew Bernier');
 INSERT INTO students (name) VALUES ('Miss Valencia Dickinson');
 INSERT INTO students (name) VALUES ('Lenny Aufderhar');
 INSERT INTO students (name) VALUES ('Shu Wisozk I');
 INSERT INTO students (name) VALUES ('Alex McDermott');
 INSERT INTO students (name) VALUES ('Fabian Stoltenberg');
 INSERT INTO students (name) VALUES ('Shelby Pagac');
 INSERT INTO students (name) VALUES ('Erica Rolfson Jr.');
 INSERT INTO students (name) VALUES ('Marcelene Maggio');
 INSERT INTO students (name) VALUES ('Miss Alfredo Wintheiser');
 INSERT INTO students (name) VALUES ('Ezequiel Bogan');
 INSERT INTO students (name) VALUES ('Marguerita Bosco');
 INSERT INTO students (name) VALUES ('Fiona Mayert');
 INSERT INTO students (name) VALUES ('Gaylord Gulgowski');
 INSERT INTO students (name) VALUES ('Branden Powlowski');
 INSERT INTO students (name) VALUES ('Ms. Jenette Leannon');
 INSERT INTO students (name) VALUES ('Weston Lakin');
 INSERT INTO students (name) VALUES ('Miss Claudie Klocko');
 INSERT INTO students (name) VALUES ('Miss Kimberely Lemke');
 INSERT INTO students (name) VALUES ('Alex Kutch V');
 INSERT INTO students (name) VALUES ('Dorcas Cartwright');
 INSERT INTO students (name) VALUES ('Myrtle Luettgen');
 INSERT INTO students (name) VALUES ('Milo Steuber');
 INSERT INTO students (name) VALUES ('Ms. Herta Bogisich');
 INSERT INTO students (name) VALUES ('Misty Muller Jr.');
 INSERT INTO students (name) VALUES ('Miss Winfred Marvin');
 INSERT INTO students (name) VALUES ('Mariana Koelpin');
 INSERT INTO students (name) VALUES ('Darin West');
 INSERT INTO students (name) VALUES ('Illa Quitzon');
 INSERT INTO students (name) VALUES ('Enrique Stehr');
 INSERT INTO students (name) VALUES ('Renae Yundt');
 INSERT INTO students (name) VALUES ('Berta Dooley');
 INSERT INTO students (name) VALUES ('Sam Kling');
 INSERT INTO students (name) VALUES ('Malka Leuschke');
 INSERT INTO students (name) VALUES ('Leora OConner');
 INSERT INTO students (name) VALUES ('Awilda Bergnaum');
 INSERT INTO students (name) VALUES ('Tamra Wolff');
 INSERT INTO students (name) VALUES ('Daniel Kautzer');
 INSERT INTO students (name) VALUES ('Matilda Boehm');
 INSERT INTO students (name) VALUES ('Mrs. Marvella Marquardt');
 INSERT INTO students (name) VALUES ('Kasi Rodriguez DDS');
 INSERT INTO students (name) VALUES ('Eugene Parisian');
 INSERT INTO students (name) VALUES ('Jeff Jaskolski');
 INSERT INTO students (name) VALUES ('Assunta McDermott');
 INSERT INTO students (name) VALUES ('Brad Schoen');
 INSERT INTO students (name) VALUES ('Lamont Padberg');
 INSERT INTO students (name) VALUES ('Hung Franecki');
 INSERT INTO students (name) VALUES ('Garry Stiedemann');
 INSERT INTO students (name) VALUES ('Johnetta Breitenberg DVM');
 INSERT INTO students (name) VALUES ('Wallace OConner Sr.');
 INSERT INTO students (name) VALUES ('Melodie Nolan');
 INSERT INTO students (name) VALUES ('Derek Runte');
 INSERT INTO students (name) VALUES ('Nancey Rosenbaum');
 INSERT INTO students (name) VALUES ('Earl Farrell');
 INSERT INTO students (name) VALUES ('Maxwell Hand');
 INSERT INTO students (name) VALUES ('Raymundo Simonis');
 INSERT INTO students (name) VALUES ('Arvilla Flatley');
 INSERT INTO students (name) VALUES ('Magda Satterfield');
 INSERT INTO students (name) VALUES ('Dr. Dick Feest');
 INSERT INTO students (name) VALUES ('Joshua Hamill V');
 INSERT INTO students (name) VALUES ('Miss Paulita Dach');
 INSERT INTO students (name) VALUES ('Lasandra Haag');
 INSERT INTO students (name) VALUES ('Valentin Berge');
 INSERT INTO students (name) VALUES ('Julianna Mueller');
 INSERT INTO students (name) VALUES ('Luigi Kris');
 INSERT INTO students (name) VALUES ('Ed Spinka');
 INSERT INTO students (name) VALUES ('Cory Wuckert PhD');
 INSERT INTO students (name) VALUES ('Rey McKenzie');
 INSERT INTO students (name) VALUES ('Billye Streich');
 INSERT INTO students (name) VALUES ('Dr. Elizabeth Koelpin');
 INSERT INTO students (name) VALUES ('Reva Bechtelar');
 INSERT INTO students (name) VALUES ('Erin Kohler II');
 INSERT INTO students (name) VALUES ('Sylvester Marks');
 INSERT INTO students (name) VALUES ('Fabiola Franecki');
 INSERT INTO students (name) VALUES ('Marcos Gulgowski');
 INSERT INTO students (name) VALUES ('Malka Miller');
 INSERT INTO students (name) VALUES ('Jennette Rice');
 INSERT INTO students (name) VALUES ('Patria Bartell');
 INSERT INTO students (name) VALUES ('Rutha Donnelly');
 INSERT INTO students (name) VALUES ('Homer Auer');
 INSERT INTO students (name) VALUES ('Elizabet Hills');
 INSERT INTO students (name) VALUES ('Agnes Larkin');
 INSERT INTO students (name) VALUES ('Valentin Renner');
 INSERT INTO students (name) VALUES ('Santo Ruecker');
 INSERT INTO students (name) VALUES ('Antonio Bins');
 INSERT INTO students (name) VALUES ('Emelina Bailey');
 INSERT INTO students (name) VALUES ('Demetria OHara');
 INSERT INTO students (name) VALUES ('Luetta Wisoky DVM');
 INSERT INTO students (name) VALUES ('Tonya Okuneva');
 INSERT INTO students (name) VALUES ('Stephen Hoppe');
 INSERT INTO students (name) VALUES ('Miki Hansen Sr.');
 INSERT INTO students (name) VALUES ('Dr. Lecia Hane');
 INSERT INTO students (name) VALUES ('Florance Pagac DVM');
 INSERT INTO students (name) VALUES ('Florine Dooley');
 INSERT INTO students (name) VALUES ('Ms. Normand Harris');
 INSERT INTO students (name) VALUES ('Kendall Osinski');
 INSERT INTO students (name) VALUES ('Syble Leffler');
 INSERT INTO students (name) VALUES ('Moriah Goyette');
 INSERT INTO students (name) VALUES ('Brianne Walter');
 INSERT INTO students (name) VALUES ('Blake Dickens');
 INSERT INTO students (name) VALUES ('Hilton Jones V');
 INSERT INTO students (name) VALUES ('Osvaldo Feeney Sr.');
 INSERT INTO students (name) VALUES ('Alvaro Bosco');
 INSERT INTO students (name) VALUES ('Ms. Nicolas Rosenbaum');
 INSERT INTO students (name) VALUES ('Troy Mueller');
 INSERT INTO students (name) VALUES ('Kenny Dibbert');
 INSERT INTO students (name) VALUES ('Ms. Carly Brekke');
 INSERT INTO students (name) VALUES ('Crysta Ferry V');
 INSERT INTO students (name) VALUES ('Clemente Konopelski PhD');
 INSERT INTO students (name) VALUES ('Mrs. Mindi Mraz');
 INSERT INTO students (name) VALUES ('Dawn Marks');
 INSERT INTO students (name) VALUES ('Vonnie Schiller Sr.');
 INSERT INTO students (name) VALUES ('Romaine Borer');
 INSERT INTO students (name) VALUES ('Bennie Hermann');
 INSERT INTO students (name) VALUES ('Chieko Jerde');
 INSERT INTO students (name) VALUES ('Ms. Walter Harvey');
 INSERT INTO students (name) VALUES ('Anton Effertz Jr.');
 INSERT INTO students (name) VALUES ('Denice Bailey');
 INSERT INTO students (name) VALUES ('Yolande Konopelski');
 INSERT INTO students (name) VALUES ('Janay Sanford');
 INSERT INTO students (name) VALUES ('Janessa Jast');
 INSERT INTO students (name) VALUES ('Miss Leticia Heller');
 INSERT INTO students (name) VALUES ('Michal Dare');
 INSERT INTO students (name) VALUES ('Leora Howe');
 INSERT INTO students (name) VALUES ('Isreal Heller');
 INSERT INTO students (name) VALUES ('Dean Anderson V');
 INSERT INTO students (name) VALUES ('Shane Cormier');
 INSERT INTO students (name) VALUES ('Ms. Silas Waters');
 INSERT INTO students (name) VALUES ('Odis Haley');
 INSERT INTO students (name) VALUES ('Mr. Tim Aufderhar');
 INSERT INTO students (name) VALUES ('Jamie Lesch');
 INSERT INTO students (name) VALUES ('Casie Champlin');
 INSERT INTO students (name) VALUES ('Michael Kautzer');
 INSERT INTO students (name) VALUES ('Sherryl Schamberger');
 INSERT INTO students (name) VALUES ('Shelby Anderson');
 INSERT INTO students (name) VALUES ('Valery Runte');
 INSERT INTO students (name) VALUES ('Mrs. Dalton Lubowitz');
 INSERT INTO students (name) VALUES ('Mr. Ginger Kunze');
 INSERT INTO students (name) VALUES ('Gracia Oara');
 INSERT INTO students (name) VALUES ('Rachele Wuckert');
 INSERT INTO students (name) VALUES ('Ann Keefe');
 INSERT INTO students (name) VALUES ('Rigoberto Aufderhar');
 INSERT INTO students (name) VALUES ('Cordie Hessel Jr.');
