## default connection pool
spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      ## MySQL
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/school_registration}
    username: ${MYSQL_USERNAME:school_db_user}
    password: ${MYSQL_PASSWORD:p@55w0rd}
  jpa:
    hibernate:
      ddl-auto: validate
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
jwt:
  secret: school-registration-app
